FROM maven:3-jdk-11

WORKDIR /app

COPY src ./src
COPY pom.xml .
COPY template-electronics.json .

RUN mvn package spring-boot:repackage

CMD java -jar target/producer-1.0-SNAPSHOT.jar template-electronics.json